---
capacity: 200
plan: free
local_db: sqlite3:/var/vcap/services/postgresql/postgresql_node.db
base_dir: /var/vcap/services/postgresql/data
mbus: nats://localhost:4222
index: 0
logging:
  level: debug
pid: /var/vcap/sys/run/postgresql_node.pid
node_id: postgresql_node_free_1
# for wardenized postgresql servie, max_db_size should not be less than 23MB
# for non-wardenized postgresql service, max_db_size should not be less than 6MB
max_db_size: 30
max_long_query: 3
max_long_tx: 30
max_db_conns: 20
db_connect_timeout: 3
db_query_timeout: 10
db_use_async_query: true
use_warden: false
warden:
  port_range:
    first: 25001
    last: 45000
  service_log_dir: /var/vcap/services/postgresql/log
  service_bin_dir:
    '9.0': /var/vcap/packages/postgresql
    '9.1': /var/vcap/packages/postgresql91
  service_common_dir: /var/vcap/store/postgresql_common
  image_dir: /var/vcap/services/postgresql/image
  service_start_timeout: 3
  filesystem_quota: false
postgresql:
  '9.0':
    host: 127.0.0.1
    port: 5432
    user: vcap
    pass: vcap
    database: postgres
    restore_bin: /var/vcap/packages/postgresql/bin/pg_restore
    dump_bin: /var/vcap/packages/postgresql/bin/pg_dump
  '9.1':
    host: 127.0.0.1
    port: 5433
    user: vcap
    pass: vcap
    database: postgres
    restore_bin: /var/vcap/packages/postgresql91/bin/pg_restore
    dump_bin: /var/vcap/packages/postgresql91/bin/pg_dump
supported_versions: ['9.0', '9.1']
default_version: '9.1'

# z_interval: 30
# fqdn_hosts: false
# op_time_limit: 6
