---
service_name: postgresql
local_db: sqlite3:/var/vcap/services/postgresql/postgresql_node.db
backup_base_dir: /tmp/backup/
backup_cmd: ":dump_bin -Fc --port=:port --host=:host --username=:user --file=:full_path/:name.dump :name"
node_id: postgresql_node_free_1
timeout: 120
postgresql:
  '9.0':
    host: localhost
    port: 5432
    user: vcap
    database: postgres
    dump_bin: /var/vcap/packages/postgresql/bin/pg_dump
  '9.1':
    host: localhost
    port: 5433
    user: vcap
    database: postgres
    dump_bin: /var/vcap/packages/postgresql91/bin/pg_dump
logging:
  level: debug
pid: /var/vcap/sys/run/postgresql_backup.pid
use_warden: false
