---
#cloud_controller_uri: api.vcap.me
service:
  name: filesystem
  version: "1.0"
  description: 'Persistent filesystem'
  plans: ['free']
  default_plan: free
  tags: []
ip_route: 172.16.218.128
index: 0
token: "0xdeadbeef"
logging:
  level: debug
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/filesystem_service.pid
#fs_type: nfs
#backends:
#  - host: 10.0.0.1
#    export: /home/nfs/backend
#    mount: /var/vcap/services/filesystem/backends/backend1
#  - host: 10.0.0.2
#    export: /home/nfs/backend
#    mount: /var/vcap/services/filesystem/backends/backend2
#  - host: 10.0.0.3
#    export: /home/nfs/backend
#    mount: /var/vcap/services/filesystem/backends/backend3
