---
capacity: 200
plan: free
local_db: sqlite3:/var/vcap/services/mongodb/mongodb_node.db
mbus: nats://localhost:4222
index: 0
base_dir: /var/vcap/services/mongodb/instances
ip_route: 127.0.0.1
logging:
  level: debug
service_log_dir: /var/vcap/sys/log/mongodb
service_bin_dir:
  "1.8": /var/vcap/packages/mongodb18
  "2.0": /var/vcap/packages/mongodb20
  "2.2": /var/vcap/packages/mongodb22
  "proxy": /var/vcap/packages/mongodb_proxy
service_common_dir: /var/vcap/store/mongodb_common
pid: /var/vcap/sys/run/mongodb_node.pid
node_id: mongodb_node_free_1

supported_versions: ["1.8", "2.0", "2.2"]
default_version: "2.2"

mongod_path:
  "1.8": "/var/vcap/packages/mongodb18/bin/mongod"
  "2.0": "/var/vcap/packages/mongodb20/bin/mongod"
  "2.2": "/var/vcap/packages/mongodb22/bin/mongod"

mongorestore_path:
  "1.8": "/var/vcap/packages/mongodb18/bin/mongorestore"
  "2.0": "/var/vcap/packages/mongodb20/bin/mongorestore"
  "2.2": "/var/vcap/packages/mongodb22/bin/mongorestore"

mongodump_path:
  "1.8": "/var/vcap/packages/mongodb18/bin/mongodump"
  "2.0": "/var/vcap/packages/mongodb20/bin/mongodump"
  "2.2": "/var/vcap/packages/mongodb22/bin/mongodump"

mongod_options:
  "1.8": ""
  "2.0": ""
  "2.2": ""

port_range:
  first: 25001
  last: 45000
max_disk: 128
migration_nfs: /mnt/migration
filesystem_quota: false
service_start_timeout: 10
tmp_dir_script: /var/vcap/jobs/mongodb_node_ng/bin/tmp_dir_ctl
# max_clients: 500
# z_interval: 30
# max_nats_payload: 1048576
# fqdn_hosts: false
# op_time_limit: 6
