---
# cloud_controller_uri: api.vcap.me
service:
  name: blob
  version: "0.51"
  description: 'Blob store'
  plans: ['free']
  default_plan: free
  tags: ['nosql']
  supported_versions: ['0.51']
ip_route: localhost
#proxy:
#   host: proxy
#   port: 8080
#   keepalive: true
index: 0
token: "0xdeadbeef"
mbus: nats://localhost:4222
logging:
  level: debug
pid: /var/vcap/sys/run/vblob_service.pid
# z_interval: 30
# check_orphan_interval: 3600
# double_check_orphan_interval: 300
plan_management:
  plans:
    free:
      low_water: 10
      high_water: 180
      #allow_over_provisioning: false
