---
cloud_controller_uri: http://api.vcap.me
service:
  name: memcached
  version: "1.4"
  description: 'Memcached in-memory cache'
  plans: ['free']
  default_plan: free
  tags: ['key-value', 'cache']
ip_route: localhost
index: 0
token: changememcachedtoken
logging:
  level: debug
mbus: nats://localhost:4222/
pid: /var/vcap/sys/run/memcached_service.pid
# z_interval: 30
